apiVersion: v1
kind: Pod
metadata:
 name: busypod
 labels:
   app: busypod
spec:
 containers:
   securityContext:
     privileged: true
 - name: busybox
   image: busybox
   command:
   - "sh"
   - "-c"
   - >
     while true; do
       sleep 3600;
     done
   volumeMounts:
   - mountPath: /test
     name: data
 securityContext:
   runAsNonRoot: true
 volumes:
 - name: data
   hostPath:
     path: /etc/test
