apiVersion: v1
kind: Pod
metadata:
  name: busypod
  labels:
    app: busypod
spec:
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    env:
    - name: TT_T
      value: "2"
    command:
    - "sh"
    - "-c"
    - >
      while true; do
        echo "$(TT_T)";
        sleep 3600;
      done
