apiVersion: v1
kind: Service
metadata:
  name: demo-auth
  namespace: demo
spec:
  selector:
    app: demo-auth
  ports:
    - port: 8443
      protocol: TCP
      name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-auth
  namespace: demo
  labels:
    app: demo-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-auth
  template:
    metadata:
      labels:
        app: demo-auth
    spec:
      containers:
        - name: metric-exporter
          image: nightfury1204/demo-auth:canary
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
