{
 "title": "m3db try",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Up",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "operator_kubevault_up{client_id=\"vault-operator\",cluster_id=\"1234\"}\t"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{client_id=\"vault-operator\",cluster_id=\"1234\"}"
    }
   ]
  },
  {
   "title": "Go routine",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "go_goroutines{client_id=\"vault-operator\",cluster_id=\"1234\"}\t"
    }
   ]
  }
 ]
}