apiVersion: operator.m3db.io/v1alpha1
kind: M3DBCluster
metadata:
  name: simple-cluster
  namespace: demo
spec:
  image: quay.io/m3db/m3dbnode:v0.7.3
  replicationFactor: 1
  numberOfShards: 16
  isolationGroups:
    - name: us-central1-a
      numInstances: 1
  podIdentityConfig:
    sources: []
  namespaces:
    - name: metrics-unagg
      options:
        bootstrapEnabled: true
        flushEnabled: true
        writesToCommitLog: true
        cleanupEnabled: true
        snapshotEnabled: true
        repairEnabled: false
        retentionOptions:
          retentionPeriod: 30m
          blockSize: 30m
          bufferFuture: 5m
          bufferPast: 5m
          blockDataExpiry: true
          blockDataExpiryAfterNotAccessPeriod: 5m
        indexOptions:
          enabled: true
          blockSize: 30m
    - name: metrics-agg
      options:
        bootstrapEnabled: true
        flushEnabled: true
        writesToCommitLog: true
        cleanupEnabled: true
        snapshotEnabled: true
        repairEnabled: false
        retentionOptions:
          retentionPeriod: 48h
          blockSize: 2h
          bufferFuture: 20m
          bufferPast: 20m
          blockDataExpiry: true
          blockDataExpiryAfterNotAccessPeriod: 5m
        indexOptions:
          enabled: true
          blockSize: 2h
