kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: secret-reader
rules:
# "" indicates the core API group
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]