apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-for-m3
  namespace: demo
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s
      scrape_timeout: 10s

    scrape_configs:
    - job_name: 'coordinator'
      static_configs:
        - targets: ['m3dbnode-simple-cluster.demo.svc:7203']
    - job_name: 'node'
      static_configs:
        - targets: ['simple-cluster-rep0-0.m3dbnode-simple-cluster.demo.svc:9004', 'simple-cluster-rep1-0.m3dbnode-simple-cluster.demo.svc:9004']
    - job_name: 'm3nsch'
      static_configs:
        - targets: ['m3nsch-agent.demo.svc:12580']