apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-for-m3
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-for-m3
  template:
    metadata:
      labels:
        app: prometheus-for-m3
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.5.0
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus/"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/
        - name: prometheus-storage
          mountPath: /prometheus/
      volumes:
      - name: prometheus-config
        configMap:
          defaultMode: 420
          name: prometheus-for-m3
      - name: prometheus-storage
        emptyDir: {}
