apiVersion: v1
kind: Service
metadata:
  name: prometheus-for-m3
  namespace: demo
spec:
  selector:
    app: prometheus-for-m3
  ports:
    - port: 9090
      protocol: TCP
      name: client
  type: ClusterIP