---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: querier
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: querier
    spec:
      containers:
      - name: querier
        image: quay.io/cortexproject/querier
        imagePullPolicy: IfNotPresent
        args:
        - -server.http-listen-port=80
        - -consul.hostname=consul.default.svc.cluster.local:8500
        - -s3.url=s3://sadf:WFKAJEM@s3.cortex-1234.us-west-1.amazonaws.com
        - -querier.frontend-address=query-frontend.default.svc.cluster.local:9095
        - -dynamodb.original-table-name=cortex
        - -dynamodb.url=dynamodb://EM@us-west-1
        - -dynamodb.periodic-table.prefix=cortex_weekly_
        - -dynamodb.periodic-table.from=2019-02-17
        - -dynamodb.daily-buckets-from=2019-02-17
        - -dynamodb.base64-buckets-from=2019-02-17
        - -dynamodb.v6-schema-from=2019-02-17
        - -dynamodb.chunk-table.from=2019-02-17
        - -memcached.hostname=memcached.default.svc.cluster.local
        - -memcached.timeout=100ms
        - -memcached.service=memcached
        - -distributor.replication-factor=1
        ports:
        - containerPort: 80
