---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: table-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: table-manager
    spec:
      containers:
      - name: table-manager
        image: quay.io/cortexproject/table-manager
        imagePullPolicy: IfNotPresent
        args:
        - -server.http-listen-port=80
        - -dynamodb.original-table-name=cortex
        - -dynamodb.url=dynamodb://AJEM@us-west-1
        - -dynamodb.periodic-table.prefix=cortex_weekly_
        - -dynamodb.periodic-table.from=2019-02-17
        - -dynamodb.chunk-table.from=2019-02-17
        - -dynamodb.periodic-table.read-throughput=3
        - -dynamodb.periodic-table.read-throughput.scale.max-capacity=3
        - -dynamodb.periodic-table.read-throughput.scale.min-capacity=1
        - -dynamodb.periodic-table.inactive-read-throughput=1
        - -dynamodb.periodic-table.inactive-write-throughput=1
        - -dynamodb.chunk-table.inactive-read-throughput.scale.max-capacity=3
        - -dynamodb.chunk-table.inactive-read-throughput.scale.min-capacity=1
        - -dynamodb.chunk-table.inactive-write-throughput.scale.max-capacity=3
        - -dynamodb.chunk-table.inactive-write-throughput.scale.min-capacity=1
        - -dynamodb.chunk-table.read-throughput=3
        - -dynamodb.chunk-table.read-throughput.scale.max-capacity=3
        - -dynamodb.chunk-table.read-throughput.scale.min-capacity=1
        - -dynamodb.chunk-table.write-throughput=3
        - -dynamodb.chunk-table.write-throughput.scale.max-capacity=3
        - -dynamodb.chunk-table.write-throughput.scale.min-capacity=1
        - -dynamodb.periodic-table.write-throughput=3
        - -dynamodb.periodic-table.write-throughput.scale.max-capacity=3
        - -dynamodb.periodic-table.write-throughput.scale.min-capacity=1
        ports:
        - containerPort: 80
