apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus-demo
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s
      scrape_timeout: 10s
    scrape_configs:
    #---------------- configuration to collect metrics from kubernetes apiserver -------------------------
    - job_name: 'kubernetes-apiservers'
      honor_labels: true
      kubernetes_sd_configs:
      - role: endpoints
      # kubernetes apiserver serve metrics on a TLS secure endpoints. so, we have to use "https" scheme
      scheme: https
      # we have to provide certificate to establish tls secure connection
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      #  bearer_token_file is required for authorizating prometheus server to kubernetes apiserver
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

    #--------------- configuration to collect metrics from nodes -----------------------
    - job_name: 'kubernetes-nodes'
      honor_labels: true
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics

    #------------------alert manager configuration-----------------------
    rule_files:
      - '/etc/rules/test.yaml'
    alerting:
      alertmanagers:
      - timeout: 10s
        path_prefix: '/'
        scheme: http
        tls_config:
          insecure_skip_verify: true
        static_configs:
        - targets:
          - 'alertmanager.monitoring.svc:9093'