apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-server
  namespace: monitoring
  labels:
    app: demo-server
spec:
  replicas: 3
  template:
    metadata:
      name: demo-server
      labels:
        app: demo-server
    spec:
      containers:
        - name: demo-server
          image: kamolhasan/demoapi:v1alpha1
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: demo-server
---
apiVersion: v1
kind: Service
metadata:
  name: demo-server
  namespace: monitoring
  labels:
    app: demo-server
spec:
  selector:
    app: demo-server
  ports:
    - port: 8080
      name: web
  type: NodePort
