apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-server
  namespace: monitoring
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      k8s-app: prometheus
  endpoints:
    - port: web