apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus-demo
  namespace: demo
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s
      scrape_timeout: 10s
    remote_read:
    - url: "http://m3coordinator.demo.svc:7201/api/v1/prom/remote/read"
      # To test reading even when local Prometheus has the data
      read_recent: true
