global:
  resolve_timeout: 5m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 6m
  receiver: 'slack'
  routes:
  - match:
      alertname: DeadMansSwitch
    receiver: 'slack'
receivers:
- name: 'slack'
  slack_configs:
  - api_url: https://hooks.slack.com/services/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
