apiVersion: v1
kind: Service
metadata:
  name: m3aggregator-rep-1
  namespace: demo
spec:
  selector:
    app: m3aggregator-rep-1
  ports:
    - port: 7201
      protocol: TCP
      name: client
    - port: 7203
      protocol: TCP
      name: metric
    - port: 6000
      protocol: TCP
      name: agg
  clusterIP: None
---
# Source: m3db-operator/templates/stateful_set.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: m3aggregator-rep-1
  namespace: demo
spec:
  serviceName: m3aggregator-rep-1
  replicas: 1
  selector:
    matchLabels:
      app: m3aggregator-rep-1
  template:
    metadata:
      labels:
        app: m3aggregator-rep-1
    spec:
      containers:
        - name: m3aggregator
          image: nightfury1204/m3aggregator:latest
          imagePullPolicy: Always
          command:
            - m3aggregator
          args:
            - "-f"
            - "/etc/m3/m3aggregator.yaml"
          ports:
            - containerPort: 7201
            - containerPort: 7203
            - containerPort: 6000
          volumeMounts:
            - name: config
              mountPath: /etc/m3/
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: m3aggregator-config
