apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: demo
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:6.2.5
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: demo
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      protocol: TCP
      name: client
  type: ClusterIP