apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - "sh"
    - "-c"
    - >
      while true; do
        sleep 3600;
      done
    volumeMounts:
    - mountPath: /etc/foo
      name: data
  volumes:
  - name: data
    secret:
      secretName: mysecret
      defaultMode: 511 # permission 0777
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: busybox
      image: busybox
      command:
      - "sh"
      - "-c"
      - >
        while true; do
          sleep 3600;
        done
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
  volumes:
  - name: foo
    secret:
      secretName: mysecret
      items:
      - key: username
        path: my-group/my-username
        mode: 511