apiVersion: v1
kind: ConfigMap
metadata:
  name: m3query-config
  namespace: demo
data:
  m3query.yaml: |
    listenAddress:
      type: "config"
      value: "0.0.0.0:7201"

    metrics:
      scope:
        prefix: "coordinator"
      prometheus:
        handlerPath: /metrics
        listenAddress: 0.0.0.0:7203 # until https://github.com/m3db/m3/issues/682 is resolved
      sanitization: prometheus
      samplingRate: 1.0
      extended: none

    clusters:
       - namespaces:
    # We created a namespace called "default" and had set it to retention "48h".
           - namespace: metrics-10s:2d
             retention: 48h
             type: unaggregated
         client:
           config:
             service:
               env: default_env
               zone: embedded
               service: m3db
               cacheDir: /var/lib/m3kv
               etcdClusters:
                 - zone: embedded
                   endpoints:
    # We have five M3DB nodes but only three are seed nodes, they are listed here.
                     - http://etcd-0.etcd:2379
                     - http://etcd-1.etcd:2379
                     - http://etcd-2.etcd:2379
           writeConsistencyLevel: majority
           readConsistencyLevel: unstrict_majority
           writeTimeout: 10s
           fetchTimeout: 15s
           connectTimeout: 20s
           writeRetry:
             initialBackoff: 500ms
             backoffFactor: 3
             maxRetries: 2
             jitter: true
           fetchRetry:
             initialBackoff: 500ms
             backoffFactor: 2
             maxRetries: 3
             jitter: true
           backgroundHealthCheckFailLimit: 4
           backgroundHealthCheckFailThrottleFactor: 0.5
    tagOptions:
      idScheme: quoted